CREATE UNIQUE INDEX IF NOT EXISTS "source_account_observations_account_run_idx" ON "source_account_observations" USING btree ("source_account_id","ingestion_run_id") WHERE "source_account_observations"."ingestion_run_id" IS NOT NULL;--> statement-breakpoint
ALTER TABLE "ad_discovery_index" DROP CONSTRAINT IF EXISTS "ad_discovery_index_target_age_check";--> statement-breakpoint
ALTER TABLE "ad_discovery_index" DROP COLUMN IF EXISTS "target_age_min";--> statement-breakpoint
ALTER TABLE "ad_discovery_index" DROP COLUMN IF EXISTS "target_age_max";--> statement-breakpoint
ALTER TABLE "ad_discovery_index" DROP COLUMN IF EXISTS "target_gender";--> statement-breakpoint
ALTER TABLE "ad_discovery_index" ADD COLUMN "latest_eu_target_age_min" integer;--> statement-breakpoint
ALTER TABLE "ad_discovery_index" ADD COLUMN "latest_eu_target_age_max" integer;--> statement-breakpoint
ALTER TABLE "ad_discovery_index" ADD COLUMN "latest_eu_target_gender" text;--> statement-breakpoint
ALTER TABLE "ad_discovery_index" ADD COLUMN "latest_uk_target_age_min" integer;--> statement-breakpoint
ALTER TABLE "ad_discovery_index" ADD COLUMN "latest_uk_target_age_max" integer;--> statement-breakpoint
ALTER TABLE "ad_discovery_index" ADD COLUMN "latest_uk_target_gender" text;--> statement-breakpoint
ALTER TABLE "ad_discovery_index" ADD COLUMN "latest_br_target_age_min" integer;--> statement-breakpoint
ALTER TABLE "ad_discovery_index" ADD COLUMN "latest_br_target_age_max" integer;--> statement-breakpoint
ALTER TABLE "ad_discovery_index" ADD COLUMN "latest_br_target_gender" text;--> statement-breakpoint
ALTER TABLE "ad_discovery_index" ADD CONSTRAINT "ad_discovery_index_eu_target_age_check" CHECK (("ad_discovery_index"."latest_eu_target_age_min" IS NULL OR ("ad_discovery_index"."latest_eu_target_age_min" >= 0 AND "ad_discovery_index"."latest_eu_target_age_min" <= 120)) AND ("ad_discovery_index"."latest_eu_target_age_max" IS NULL OR ("ad_discovery_index"."latest_eu_target_age_max" >= 0 AND "ad_discovery_index"."latest_eu_target_age_max" <= 120)) AND ("ad_discovery_index"."latest_eu_target_age_min" IS NULL OR "ad_discovery_index"."latest_eu_target_age_max" IS NULL OR "ad_discovery_index"."latest_eu_target_age_min" <= "ad_discovery_index"."latest_eu_target_age_max"));--> statement-breakpoint
ALTER TABLE "ad_discovery_index" ADD CONSTRAINT "ad_discovery_index_uk_target_age_check" CHECK (("ad_discovery_index"."latest_uk_target_age_min" IS NULL OR ("ad_discovery_index"."latest_uk_target_age_min" >= 0 AND "ad_discovery_index"."latest_uk_target_age_min" <= 120)) AND ("ad_discovery_index"."latest_uk_target_age_max" IS NULL OR ("ad_discovery_index"."latest_uk_target_age_max" >= 0 AND "ad_discovery_index"."latest_uk_target_age_max" <= 120)) AND ("ad_discovery_index"."latest_uk_target_age_min" IS NULL OR "ad_discovery_index"."latest_uk_target_age_max" IS NULL OR "ad_discovery_index"."latest_uk_target_age_min" <= "ad_discovery_index"."latest_uk_target_age_max"));--> statement-breakpoint
ALTER TABLE "ad_discovery_index" ADD CONSTRAINT "ad_discovery_index_br_target_age_check" CHECK (("ad_discovery_index"."latest_br_target_age_min" IS NULL OR ("ad_discovery_index"."latest_br_target_age_min" >= 0 AND "ad_discovery_index"."latest_br_target_age_min" <= 120)) AND ("ad_discovery_index"."latest_br_target_age_max" IS NULL OR ("ad_discovery_index"."latest_br_target_age_max" >= 0 AND "ad_discovery_index"."latest_br_target_age_max" <= 120)) AND ("ad_discovery_index"."latest_br_target_age_min" IS NULL OR "ad_discovery_index"."latest_br_target_age_max" IS NULL OR "ad_discovery_index"."latest_br_target_age_min" <= "ad_discovery_index"."latest_br_target_age_max"));